apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-inventario-api
  labels:
    app: api-inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
        - name: api-inventario-container
          image: jo4ovictor/gameinventarioapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-inventario-service
spec:
  selector:
    app: inventario
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
  type: LoadBalancer