apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-catalogo-api
  labels:
    app: api-catalogo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo
  template:
    metadata:
      labels:
        app: catalogo
    spec:
      containers:
        - name: api-catalogo-container
          image: jo4ovictor/gamecatalogoapi:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-catalogo-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: catalogo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-catalogo-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: catalogo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  